// NIGHT: unshielded token. Atomic unit = Star. 1 NIGHT = 10^6 Stars.
export const STARS_PER_NIGHT = 1_000_000n;
export const NIGHT_TOKEN_TYPE = '0000000000000000000000000000000000000000000000000000000000000000';

// DUST: generated by NIGHT, separate ledger. Atomic unit = Speck. 1 DUST = 10^15 Specks.
export const SPECKS_PER_DUST = 1_000_000_000_000_000n;

/** Extract the native NIGHT balance (in stars) from an unshielded balances record. */
export function getNightBalance(unshieldedBalances: Record<string, bigint>): bigint {
  return unshieldedBalances[NIGHT_TOKEN_TYPE] ?? 0n;
}

/** Convert stars to NIGHT (integer division). */
export function starsToNight(stars: bigint): string {
  return (stars / STARS_PER_NIGHT).toLocaleString();
}

/** Convert specks to DUST (integer division). */
export function specksToDust(specks: bigint): string {
  return (specks / SPECKS_PER_DUST).toLocaleString();
}

export interface TokenBalance {
  color: string;
  amount: bigint;
}

/**
 * Extract structured balances from a balance record.
 * Returns the NIGHT balance (in stars) and a list of other token balances.
 */
export function extractBalances(balances: Record<string, bigint>): { night: bigint; tokens: TokenBalance[] } {
  const { [NIGHT_TOKEN_TYPE]: night = 0n, ...rest } = balances;
  return {
    night,
    tokens: Object.entries(rest).map(([color, amount]) => ({ color, amount })),
  };
}
